# Generated by Django 5.2.7 on 2025-10-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_funcionario_mesa_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
