# Generated by Django 5.2.7 on 2025-10-15 20:38

import django.db.models.deletion
import pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_pedido_options_remove_pedido_itens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outros',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido',
        ),
        migrations.CreateModel(
            name='Refrigerante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('imagem_width', models.PositiveIntegerField(blank=True, null=True)),
                ('imagem_height', models.PositiveIntegerField(blank=True, null=True)),
                ('imagem', pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['AVIF'], grid_columns=12, height_field='imagem_height', pixel_densities=[1, 2], upload_to='refrigerantes', verbose_name='Imagem', width_field='imagem_width')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Refrigerante',
                'verbose_name_plural': 'Refrigerantes',
            },
        ),
        migrations.DeleteModel(
            name='Bebida',
        ),
        migrations.DeleteModel(
            name='Outros',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
