# Generated by Django 5.2.7 on 2025-10-16 19:06

import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_item_alter_sobremesa_imagem_outros_pedido_pedidoitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='porcao',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='sobremesa',
            name='imagem',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['AVIF'], grid_columns=12, height_field='imagem_height', pixel_densities=[1, 2], upload_to='sobremesa', verbose_name='Imagem', width_field='imagem_width'),
        ),
        migrations.DeleteModel(
            name='Outros',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
        migrations.DeleteModel(
            name='Porcao',
        ),
    ]
