# Generated by Django 5.2.7 on 2025-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_delete_item_remove_pedido_mesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='bordas',
            field=models.ManyToManyField(blank=True, related_name='bordas', to='pedidos.extra'),
        ),
    ]
