# Generated by Django 5.2.7 on 2025-10-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_pizza_bordas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='bordas',
            field=models.ManyToManyField(blank=True, related_name='bordas', to='pedidos.borda'),
        ),
    ]
