# Generated by Django 5.2.7 on 2025-10-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_gelo_gelolimao_limao'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerante',
            name='Gelo',
            field=models.ManyToManyField(blank=True, related_name='gelo', to='pedidos.gelo'),
        ),
        migrations.AddField(
            model_name='refrigerante',
            name='GeloLimao',
            field=models.ManyToManyField(blank=True, related_name='gelolimao', to='pedidos.gelolimao'),
        ),
        migrations.AddField(
            model_name='refrigerante',
            name='Limao',
            field=models.ManyToManyField(blank=True, related_name='limao', to='pedidos.limao'),
        ),
    ]
