# Generated by Django 5.2.7 on 2025-10-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_refrigerante_gelo_refrigerante_gelolimao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refrigerante',
            name='Gelo',
        ),
        migrations.RemoveField(
            model_name='refrigerante',
            name='Limao',
        ),
    ]
