# Generated by Django 5.2.7 on 2025-10-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_remove_refrigerante_gelo_remove_refrigerante_limao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gelo',
        ),
        migrations.DeleteModel(
            name='Limao',
        ),
    ]
