# Generated by Django 5.2.7 on 2025-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_mesas', models.PositiveIntegerField(default=10, verbose_name='Quantidade de Mesas')),
            ],
            options={
                'verbose_name': 'Configuração de Mesas',
                'verbose_name_plural': 'Configuração de Mesas',
            },
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['numero'], 'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AlterField(
            model_name='mesa',
            name='status',
            field=models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada')], default='livre', max_length=10),
        ),
    ]
