# Generated by Django 5.2.7 on 2025-10-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_pedido_status_alter_pedido_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('pizzas', 'Pizzas'), ('bebidas', 'Bebidas'), ('cervejas', 'Cervejas'), ('sobremesas', 'Sobremesas'), ('porcoes', 'Porções'), ('outros', 'Outros')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
