# Generated by Django 5.2.7 on 2025-10-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('pizzas', 'Pizzas'), ('refrigerantes', 'Refrigerantes'), ('cervejas', 'Cervejas'), ('sobremesas', 'Sobremesas'), ('porcoes', 'Porções'), ('outros', 'Outros')], max_length=20),
        ),
    ]
