# Generated by Django 5.2.7 on 2025-10-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_alter_item_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='itens',
        ),
    ]
