# Generated by Django 5.2.7 on 2025-10-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_remove_pedido_itens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
