# Generated by Django 5.2.7 on 2025-10-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
